# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "postprocess_ltrretriever"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - "bioconda::trf"
  - "bioconda::mdust==2006.10.17-6"
  - "bioconda::tesorter"