project:
  type: website
  output-dir: "../docs"

website:
  title: "EDTA: Nextflow Documentation"
  page-navigation: true
  search:
    location: navbar
    type: textbox

  repo-url: https://github.com/oushujun/EDTA
  repo-actions: [issue]

  navbar:
    left:
      - href: index.qmd
        text: Home
      - faq.qmd

  sidebar:
      style: "docked"
      contents:
        - quickstart.qmd
        - section: "Manual"
          contents:
            - installation.qmd
            - usage.qmd
            - advanced_usage.qmd
            - output.qmd
        - pipeline_overview.qmd
        - section: "Help"
          contents:
            - common_problems.qmd
            - faq.qmd
            - getting_help.qmd
        - citation.qmd
        - license.qmd
        
format:
  html:
    # Maybe slate
    theme: darkly
    css: styles.css
    toc: true
    
