name: EDTA Nextflow CI
on:
  pull_request:

env:
  NXF_ANSI_LOG: false
  NFT_WORKDIR: "~"
  NFT_DIFF: "pdiff"
  NFT_DIFF_ARGS: "--line-numbers --expand-tabs=2"
  NXF_SINGULARITY_CACHEDIR: ${{ github.workspace }}/.singularity
  NXF_SINGULARITY_LIBRARYDIR: ${{ github.workspace }}/.singularity

concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: true

jobs:
  nf-test-changes:
    name: Check for changes
    runs-on: ubuntu-latest
    outputs:
      nf_test_files: ${{ steps.list.outputs.components }}
    steps:
      - uses: actions/checkout@v4.2.1
        with:
          fetch-depth: 0

      - name: List nf-test files
        id: list
        uses: adamrtalbot/detect-nf-test-changes@v0.0.4
        with:
          head: ${{ github.sha }}
          base: origin/${{ github.base_ref }}
          include: .github/include.yaml

      - name: print list of nf-test files
        run: |
          echo ${{ steps.list.outputs.components }}

  test:
    name: ${{ matrix.nf_test_files }} ${{ matrix.profile }} NF-${{ matrix.NXF_VER }}
    needs: [nf-test-changes]
    if: needs.nf-test-changes.outputs.nf_test_files != '[]'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        NXF_VER:
          - "24.04.2"

        nf_test_files: ["${{ fromJson(needs.nf-test-changes.outputs.nf_test_files) }}"]
        profile: [conda, docker, singularity]

    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v4.2.1

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: "${{ matrix.NXF_VER }}"

      - uses: actions/setup-python@v5.2.0
        with:
          python-version: "3.11"
          architecture: "x64"

      - name: Install pdiff to see diff between nf-test snapshots
        run: |
          python -m pip install --upgrade pip
          pip install pdiff

      - uses: nf-core/setup-nf-test@v1.1.2
        with:
          version: 0.9.0
      
      - name: Setup apptainer
        if: matrix.profile == 'singularity'
        uses: eWaterCycle/setup-apptainer@main

      - name: Set up Singularity
        if: matrix.profile == 'singularity'
        run: |
          mkdir -p $NXF_SINGULARITY_CACHEDIR
          mkdir -p $NXF_SINGULARITY_LIBRARYDIR

      - name: Run nf-test
        run: |
          nf-test test --verbose ${{ matrix.nf_test_files }} --profile "+${{ matrix.profile }}"

  confirm-pass:
    runs-on: ubuntu-latest
    needs: [test]
    if: always()
    steps:
      - name: All tests ok
        if: ${{ !contains(needs.*.result, 'failure') }}
        run: exit 0
      - name: One or more tests failed
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1

      - name: debug-print
        if: always()
        run: |
          echo "toJSON(needs) = ${{ toJSON(needs) }}"
          echo "toJSON(needs.*.result) = ${{ toJSON(needs.*.result) }}"
